### ISSUE TITLE
Missing weak keywords?

### ISSUE THREAD

**Issue by jakevossen5** [rust-lang/reference#1007]
Currently comparing: [this line line symbol.rs](https://github.com/rust-lang/rust/blob/9d9c2c92b834c430f102ea96f65119e37320776e/compiler/rustc_span/src/symbol.rs#L96) and [this file](https://github.com/rust-lang/reference/blob/8db4edd7eab7931859713ac8016ba123ce42b061/src/keywords.md) and it looks like `auto`, `catch`, `default`, `macro_rules`, `raw`, and `union` are missing from the reference?

Is this intentional? If not, I should be able to add a quick PR to fix.

**Comment by ehuss** [comment]
Hi, thanks for taking a look!  The reference does not document nightly features, so I believe `auto`, `catch`, `default`, and `raw` don't need to be mentioned as they don't affect stable rust parsing. `union` is already documented.  The only one that I think could be added is `macro_rules`. It looks like that was changed not too long ago (https://github.com/rust-lang/rust/pull/69186).  If you want to update that, it would be appreciated!
