### ISSUE TITLE
Glossary: add "crate" and "module"

### ISSUE THREAD

**Issue by cmcqueen** [rust-lang/reference#1015]
Please add "crate" and "module" to the glossary. As someone coming from Python, I'm a bit unsure of what Rust terminology to use instead of Python's "package".

**Comment by ehuss** [comment]
Yea, it definitely can be confusing, especially when the same term is used in different ways. I have posted #1016 with some definitions. You may also find some definitions in the Cargo glossary for [crate](https://doc.rust-lang.org/cargo/appendix/glossary.html#crate) and [package](https://doc.rust-lang.org/cargo/appendix/glossary.html#package).

The following is a rough translation:

Python       | Rust
-------------|------ 
project      | package or project (a Cargo concept)
root package | crate or "crate root"
subpackage   | module 
module       | module

Rust does not differentiate between leaves and nodes in the module tree, it just calls them all "modules" whereas Python calls inner nodes "subpackages".
