### ISSUE TITLE
Mistake on where attributes are allowed in StructExpr and more

### ISSUE THREAD

**Issue by YizhePKU** [rust-lang/reference#1021]
According to the [reference](https://doc.rust-lang.org/nightly/reference/expressions/struct-expr.html), only inner attributes are allowed in an StructExpr:

```
StructExprStruct :
   PathInExpression { InnerAttribute* (StructExprFields | StructBase)? }
```

However, this seems not to be the behaviour of rustc. rustc instead accepts only outer attributes for each field, but not inner attributes for the entire expression.

For example, this compiles in rustc:

``` rust
struct S { x: i64, y: i64 }
fn main() {
    let s =  S { x: 1, #[deprecated] y: 2};
}
```

But not this:

``` rust
struct S { x: i64, y: i64 }
fn main() {
    let s =  S { #![deprecated] x: 1, y: 2};
}
```

**Comment by ehuss** [comment]
They were accepted syntactically, but that was recently removed in nightly in https://github.com/rust-lang/rust/pull/83312.  There is discussion in https://github.com/rust-lang/rust/issues/84879 about reverting that change.
