### ISSUE TITLE
`TypeAlias` syntax missing a `TypeParamBounds`

### ISSUE THREAD

**Issue by GilRtr** [rust-lang/reference#1032]
this is valid syntactically:
```rs
type TypeAlias: TraitBound = SomeType;
```
however it is not part of the reference.

expectation:
> **<sup>Syntax</sup>**\
> _TypeAlias_ :\
> &nbsp;&nbsp; `type` [IDENTIFIER]()&nbsp;[_GenericParams_]()<sup>?</sup> ( `:` [TypeParamBounds]() )<sup>?</sup> [_WhereClause_]()<sup>?</sup> ( `=` [_Type_]() )<sup>?</sup> `;`

*should be stated that this syntax is only useful in the context of an associated type and will yield ``bounds on `type`s in this context have no effect`` anywhere else.

edit: I accidently pressed `enter` before writing the description

**Comment by ehuss** [comment]
Thanks for the eagle eye!  Looks like I missed this as part of the grand parser unification (#927).  Would you be willing to open a PR?
