### ISSUE TITLE
12.6 Visibility and Privacy Example Bug?

### ISSUE THREAD

**Issue by davyzhu** [rust-lang/reference#1039]
First Example in https://doc.rust-lang.org/reference/visibility-and-privacy.html
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=215908aa41200a4e9ce3841cff3dd978

```
   Compiling playground v0.0.1 (/playground)
error[E0432]: unresolved import `crate_helper_module`
  --> src/lib.rs:22:9
   |
22 |     use crate_helper_module;
   |         ^^^^^^^^^^^^^^^^^^^ no external crate `crate_helper_module`
```

This line should be changed to    
```
use crate::crate_helper_module;
```

**Comment by bjorn3** [comment]
It is currect for the 2015 edition.

**Comment by ehuss** [comment]
I posted #1041 to change things to default to 2018 to fix this.
