### ISSUE TITLE
2021: Switch default to 2021

### ISSUE THREAD

**Issue by ehuss** [rust-lang/reference#1065]
The default for tests needs to be update to 2021. This involves changing [this line](https://github.com/rust-lang/reference/blob/ab60513a3a5a0591e237fddff5d027a982648392/book.toml#L14) to 2021, and fixing any broken tests.

Note that this is blocked on a new mdbook being published (I will try to do that soon). There will also need to be a new mdbook published once 2021 is stabilized on nightly.

**Comment by mattheww** [comment]
I have run `mdbook test` using current mdbook master and edition 2021, and the only failing test is the one addressed by #1110.

(mdbook 0.4.13 isn't new enough to allow changing `book.toml` yet, at least
when using stable rustc.)

**Comment by ehuss** [comment]
Thanks for taking a look @mattheww!  The reference tests with nightly rustc, so I think using 0.4.13 should be fine for now. I'll look at pushing an update to resolve that, though.
