### ISSUE TITLE
Document what `modifiers` does in `link` attr

### ISSUE THREAD

**Issue by Nashenas88** [rust-lang/reference#1086]
An example usage can be found at https://github.com/rust-lang/rust/blob/4c9896f279357896d31d811fddc2025d72259498/library/unwind/src/libunwind.rs#L91:

```rust
#[cfg_attr(
    all(feature = "llvm-libunwind", any(target_os = "fuchsia", target_os = "linux")),
    link(name = "unwind", kind = "static", modifiers = "-bundle")
)]
extern "C-unwind" {
    pub fn _Unwind_Resume(exception: *mut _Unwind_Exception) -> !;
}
```

**Comment by petrochenkov** [comment]
The modifiers are not yet described if the reference because they are not yet stable, the documentation for them can be found in the corresponding RFC - https://github.com/rust-lang/rfcs/blob/master/text/2951-native-link-modifiers.md

**Comment by ehuss** [comment]
Yea, closing as the reference does not describe unstable features.
