### ISSUE TITLE
Document that closure expressions don't always produce closure values

### ISSUE THREAD

**Issue by mheiber** [rust-lang/reference#1121]
The documentation incorrectly says that closure expressions always produce values of closure types.
Here's a repro of a closure expression producing a funciton pointer type:

```rust
fn main() {
    takes_ptr(|| println!("in closure expression"))
}

fn takes_ptr(_: fn()) {}
```

> It looks like internally these things are called `ClosureFnPointer`s

At least the following parts of the docs could be updated if I understand correctly.

- In https://doc.rust-lang.org/reference/expressions/closure-expr.html: "A closure expression, also know as a lambda expression or a lambda, defines a closure type ..."
- In https://doc.rust-lang.org/reference/types/closure.html "A closure expression produces a closure value with a unique, anonymous type that cannot be written out."

I think it's worth documenting, since (anecdotally) I was surprised by the behavior several times. In each of these cases small changes to the code lead to the need to think about the problem very differently:
- putting functions in a vec
- branching to decide which function to call
- and when calling a function that expects a function pointer in a way that wasn't obvious. This happened to me with https://github.com/nannou-org/nannou's api: in `nannou::app(model).view(view)`, `model: ModelFn<M>` and `view: ViewFn<M>`. I assumed these were wrappers around `Fn` and tested my hypothesis like this `nannou::app(|arg| app(arg))....`. This worked, so I assumed I could store state in the function. But then as soon as I did anything non-trivial in the closure, I got a type error. 

An alternative to documentation is to deprecate the feature: it seems like a design-time footgun.

 Happy to PR to The Reference document the feature.

**Comment by ehuss** [comment]
I think this is documented in the [Call traits and coercions](https://doc.rust-lang.org/reference/types/closure.html#call-traits-and-coercions) section.  It is a closure type. There is just a special case where a closure that does not capture anything can also be coerced to a function pointer.  So in your example, it is ending up as a function pointer due to coercion. Does that sufficiently explain what you are seeing?

**Comment by mheiber** [comment]
Thanks for the reference, that's exactly what I was looking for. I'll read the reference more carefully. Thank you
