### ISSUE TITLE
Missing char-> uX as casts in Type cast expressions

### ISSUE THREAD

**Issue by nico-abram** [rust-lang/reference#1122]
This page https://doc.rust-lang.org/nightly/reference/expressions/operator-expr.html?highlight=cast#type-cast-expressions

Does not curently mention char -> uX as casts

**Comment by ehuss** [comment]
If you're referring to an expression such as `'c' as u32`, I believe that is covered by the `bool or char | Integer type` entry in the table and the [Primitive to integer cast](https://doc.rust-lang.org/nightly/reference/expressions/operator-expr.html#primitive-to-integer-cast) section.  Can you say more about what appears to be missing?

**Comment by nico-abram** [comment]
You are completely right. Sorry for the useless issue.
