### ISSUE TITLE
Tokens `true` and `false` are defined twice.

### ISSUE THREAD

**Issue by mattheww** [rust-lang/reference#1167]
At present, `true` and `false` are each defined twice in the `Lexer` blocks: once as keywords and once as part of BOOLEAN_LITERAL.

I think we should do one of:

 - change the BOOLEAN_LITERAL definition to use KW_TRUE | KW_FALSE rather than `true` | `false`

 - remove BOOLEAN_LITERAL and update literal-expr.md and patterns.md accordingly

The second is a larger change but seems more in the spirit of #939. It would also make the text

> Any kind of literal (string, integer, etc) with any suffix is valid as a token, and can be passed to a macro without producing an error

in tokens.md no longer appear to make a claim about suffixes following `true` and `false`.

**Comment by Havvy** [comment]
I was asked if I had an opinion on this. I do not; the nitty gritty grammar decisions aren't something I've spent much brainpower thinking about.
