### ISSUE TITLE
Dead link in glossary page.

### ISSUE THREAD

**Issue by gimbles** [rust-lang/reference#1175]
https://doc.rust-lang.org/reference/glossary.html

The bastion of the turbofish link is dead.
![image](https://user-images.githubusercontent.com/93856041/156913313-9e7896ee-0251-4a2e-8da2-c29c97339922.png)
![image](https://user-images.githubusercontent.com/93856041/156913319-d0702240-e613-45d1-8321-fb334e54c06e.png)

**Comment by Havvy** [comment]
Fixed in nightly already by #1161 (You can test yourself by going to `/nightly/reference/glossary.html`)

Thanks for the issue report nonetheless.
