### ISSUE TITLE
Repetition trailing separator in Macros By Example Syntax

### ISSUE THREAD

**Issue by fujiapple852** [rust-lang/reference#1178]
The Macros By Example syntax does not seem to cover the case where the separator is specified inside the round braces (trailing separator):

> _MacroMatch_ :\
> &nbsp;&nbsp; &nbsp;&nbsp; [_Token_]<sub>_except `$` and [delimiters]_</sub>\
> &nbsp;&nbsp; | _MacroMatcher_\
> &nbsp;&nbsp; | `$` ( [IDENTIFIER_OR_KEYWORD] <sub>_except `crate`_</sub> | [RAW_IDENTIFIER] | `_` ) `:` _MacroFragSpec_\
> &nbsp;&nbsp; | `$` `(` _MacroMatch_<sup>+</sup> `)` _MacroRepSep_<sup>?</sup> _MacroRepOp_

https://github.com/rust-lang/reference/blob/71cdfb9fb5926e19890f381b2dc110a159113a33/src/macros-by-example.md?plain=1#L27

The only place I have seen this documented is in the [Trailing separators](https://danielkeep.github.io/tlborm/book/pat-trailing-separators.html) section of The Little Book of Rust Macros and these do [work](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=8f612be272c2d91b1a806ed90be55098).

I'm not clear on what the correct production rule should be for this in the grammar to avoid ambiguity given the separator is optional in both places.

**Comment by bjorn3** [comment]
In something like `$($foo:ident,)*` the `,` is parsed as `MacroMatch` just like `$foo:ident`. It doesn't have any special casing.

**Comment by fujiapple852** [comment]
That makes sense, thanks for clarifying.
