### ISSUE TITLE
[proc macros] confusing statement

### ISSUE THREAD

**Issue by evgeniy-terekhin** [rust-lang/reference#1209]
link: https://doc.rust-lang.org/reference/procedural-macros.html#the-proc_macro-crate

When token span's are mentioned there is this phrase.

All tokens have an associated Span. A Span is an opaque value that _**cannot be modified**_ but can be manufactured. Spans represent an extent of source code within a program and are primarily used for error reporting. You _**can modify**_ the Span of any token.

To me it seems like a contradiction. I would have submit a fix straight away but I am not sure how to express it correctly.

**Comment by bjorn3** [comment]
You can change what span a token has, but you can't change for example the start or end character of a span, or change it's file. This means that if you want to change the span of a token, you either have to get it from another token, or you have to use `Span::call_site()` or `Span::def_site()` to get the span of the macro invocation cq the macro definition.

**Comment by evgeniy-terekhin** [comment]
@bjorn3 thanks for the clarification. Maybe somthing like whar you wrote should be added to the reference to make the phrasing less confusing.

**Comment by Havvy** [comment]
It might be better to say that spans are immutable while the span a token has is not.
