### ISSUE TITLE
What is the UB behaviour of accessing *mut through &T

### ISSUE THREAD

**Issue by EvanTheB** [rust-lang/reference#1227]
https://github.com/rust-lang/reference/blob/683bfe5cd64d589c6a1645312ab5f93b6385ccbb/src/behavior-considered-undefined.md?plain=1#L31

> Mutating immutable data. All data inside a [const](https://doc.rust-lang.org/reference/items/constant-items.html) item is immutable. Moreover, all data reached through a shared reference or data owned by an immutable binding is immutable, unless that data is contained within an [UnsafeCell<U>](https://doc.rust-lang.org/std/cell/struct.UnsafeCell.html).

I was wondering how to use *mut pointers in more safe way, I asked this question: https://stackoverflow.com/questions/72541045

A user responded that I read this paragraph wrong, and that modifying data through both `UnsafeCell<U>` AND `*mut U` would not be UB. Does the above paragraph need to mention raw pointers?

**Comment by bjorn3** [comment]
No, if the `*mut U` is derived from a sjared reference without it being of type `&UnsafeCell<U>` or similar, writing through the `*mut U` is still UB.

**Comment by ChayimFriedman2** [comment]
@bjorn3 I'm the bespoken user. The OP talks about a case like:
```rust
struct Foo(*mut i32);

unsafe fn bar(v: &Foo) {
    *v.0 = 123;
}
```
**Not** something like:
```rust
struct Foo(i32);

unsafe fn bar(v: &Foo) {
    *(&v.0 as *const i32 as *mut i32) = 123;
}
```
Are you referring to that too, or did you talk about the cast case?

**Comment by bjorn3** [comment]
I see. The first snippet is fine.

**Comment by EvanTheB** [comment]
Thank you for your help.

Maybe what I am confused about is that rust does not consider the `*mut T` to 'own' the T. Nor is the T 'inside' the item. Nor is the T 'reached through' the reference.

I want treat my `*mut T` as owning the data, so I wrote a small wrapper: 

```
/// This struct exists only to force *mut to be used in a mutable context
/// For example, to prevent this:
///
/// fn mutate(ptr: *mut T) {}
/// fn (&self) {
///     mutate(self.ptr)
/// }
///
#[derive(Debug)]
pub struct CPtr<T> {
    ptr: *mut T,
}

impl<T> CPtr<T> {
    pub fn new(ptr: *mut T) -> Self {
        Self { ptr }
    }

    pub fn as_ptr(&self) -> *const T {
        self.ptr
    }

    pub fn as_mut_ptr(&mut self) -> *mut T {
        self.ptr
    }
}
```

I am suprised such a wrapper does not already exist in the stdlib, so I suspect that it does and I have missed it.

**Comment by ChayimFriedman2** [comment]
This wrapper is called `Unique` and is an internal implementation detail, although it is considered owned by rustc and Stacked Borrowed, at least currently. It is used to implement e.g. `Box`, but was deemed not common enough to be exposed.
