### ISSUE TITLE
Contradictory definition of 'STRING_LITERAL'

### ISSUE THREAD

**Issue by EvgenHi** [rust-lang/reference#1252]
[STRING_LITERAL](https://doc.rust-lang.org/reference/tokens.html#string-literals) definition says:
![Screenshot from 2022-08-16 22-34-51](https://user-images.githubusercontent.com/91457298/184971506-82887a9e-9c4f-4455-93a4-9ad0ed1539c2.png)
Where [_IsolatedCR_](https://doc.rust-lang.org/reference/comments.html#comments) is:
![Screenshot from 2022-08-16 22-43-45](https://user-images.githubusercontent.com/91457298/184969910-96a2a115-7d25-457a-943f-54b3e64acb6b.png)
And  [ASCII_ESCAPE](https://doc.rust-lang.org/reference/tokens.html#ascii-escapes) is:
![Screenshot from 2022-08-16 22-50-17](https://user-images.githubusercontent.com/91457298/184972447-637d852c-2db9-4479-9877-cedd0fb17af9.png)

But look, there is no compile time error:
![Screenshot from 2022-08-16 23-16-45](https://user-images.githubusercontent.com/91457298/184976999-a30e06c1-7745-45c7-bac1-8def137bf9fa.png)

My question:
Is this a human error or some feature of the lexer implementation which I don't know about?

**Comment by bjorn3** [comment]
The ASCII_ESCAPE `\r` and IsolatedCR are not the same. The former is literally writing the two characters `\` and `r` while the later is the single character called cariage return.

**Comment by EvgenHi** [comment]
Understood thanks. But still there is an inconsistency. If _IsolatedCR_ is a single character, it should be mentioned, because, refereing to this:
![Screenshot from 2022-08-17 00-14-15](https://user-images.githubusercontent.com/91457298/184986715-0637b737-3fa4-46e9-9dea-7b78d809ca1c.png)
and the _IsolatedCR_ definition:
![Screenshot from 2022-08-16 22-43-45](https://user-images.githubusercontent.com/91457298/184988051-686834f2-bba7-46ee-b1ff-38d3f9d9286b.png)
 I deduce that  _IsolatedCR_ is exactly two characters.
