### ISSUE TITLE
[Feature Request]: plans to support OpenSearch?

### ISSUE THREAD

**Issue by LollipopFt** [rust-lang/reference#1255]
are there any plans to support [https://www.opensearch.org/]() like `docs.rs` or `lib.rs`? this would facilitate searching for specific keywords. (applies to both reference book and the rust book)

**Comment by ehuss** [comment]
I think it is unlikely.  There is a tracking issue at https://github.com/rust-lang/rust/issues/24899 for this, so closing in favor of that.
