### ISSUE TITLE
Items must show what paths they make available.

### ISSUE THREAD

**Issue by Havvy** [rust-lang/reference#129]
Every item should declare what paths it adds. We can say that the canonical path for an item is its *path prefix* followed by `::` followed by the item's *path component*. Modules and implementations change the path prefix, while everything except implementations define new path components.

- [ ] constants
- [ ] enumerations
- [ ] extern crates
- [ ] external blocks
- [ ] functions
- [ ] implementations
- [ ] modules
- [ ] statics
- [ ] structs
- [ ] traits
- [ ] type aliases
- [ ] unions
- [ ] use declarations

**Comment by ehuss** [comment]
Posted #1052 with what I think should close this out.
