### ISSUE TITLE
Clarify whether inline assembly `nomem` implies `nostack`

### ISSUE THREAD

**Issue by lukas-code** [rust-lang/reference#1350]
Location: https://doc.rust-lang.org/nightly/reference/inline-assembly.html#options

i.e. is the following UB:
```rust
pub fn foo() {
    unsafe { core::arch::asm!("push rax", "pop rax", options(nomem)) }
}
```

This code obviously does write to memory, but the reference only talks about global variables for `nomem`, which make me think this probably fine? It would be nice to clarify whether `nomem` inline assembly is allowed to access to stack at all.

**Comment by Freax13** [comment]
I think this code would not be UB.

> The set of memory locations that assembly code is allowed to read and write are the same as those allowed for an FFI function.  [...] If the `readonly` option is set, then only memory reads are allowed.  If the `nomem` option is set then no reads or writes to memory are allowed. [...] **These rules do not apply to memory which is private to the asm code, such as stack space allocated within the asm block.**

([source](https://doc.rust-lang.org/reference/inline-assembly.html), emphasis mine)

**Comment by lukas-code** [comment]
@Freax13 Thanks, I must have missed that.
