### ISSUE TITLE
asm: Are input registers guaranteed to be written in left-to-right order?

### ISSUE THREAD

**Issue by jmillikin** [rust-lang/reference#1353]
Context: https://github.com/google/gvisor/issues/8894

I would like to be able to manually control the order in which inputs to an `asm!` block are written to their assigned registers, to ensure that Linux syscalls have the specific instruction pattern `mov eax, {syscall_nr}; syscall` . The inline assembly reference currently offers this guarantee for output operands:

> Operand expressions are evaluated from left to right, just like function call arguments. After the `asm!` has executed, outputs are written to in left to right order.

Some testing shows that rustc v1.64 currently generates `mov` instructions for *inputs* in left-to-right order as well, which offers an easy solution to my problem. Is this behavior guaranteed, and if so, can that guarantee be added to the reference page at https://doc.rust-lang.org/reference/inline-assembly.html#operand-type ?

---

With current code (https://github.com/jmillikin/rust-linux-syscall/blob/v1.0.0/linux-syscall/arch/x86_64/syscall_asm.rs):

```
core::arch::asm!(
	"syscall",
	in("rax") u32::from(Into::<$crate::Syscall>::into($nr)),
	in("rdi") $a1,
	in("rsi") $a2,
	in("rdx") $a3,
	lateout("rcx") _,
	lateout("r11") _,
	lateout("rax") out_rax,
	options(nostack),
);
```
||
\  /
```
  201263:       b8 01 00 00 00          mov    eax,0x1
  201268:       89 f7                   mov    edi,esi
  20126a:       48 89 d6                mov    rsi,rdx
  20126d:       48 89 ca                mov    rdx,rcx
  201270:       0f 05                   syscall
```

Adjusting the order of input register declarations:

```
core::arch::asm!(
	"syscall",
	in("rdi") $a1,
	in("rsi") $a2,
	in("rdx") $a3,
	in("rax") u32::from(Into::<$crate::Syscall>::into($nr)),
	lateout("rcx") _,
	lateout("r11") _,
	lateout("rax") out_rax,
	options(nostack),
);
```
||
\  /
```
  201263:       89 f7                   mov    edi,esi
  201265:       48 89 d6                mov    rsi,rdx
  201268:       48 89 ca                mov    rdx,rcx
  20126b:       b8 01 00 00 00          mov    eax,0x1
  201270:       0f 05                   syscall
```

**Comment by bjorn3** [comment]
No, I don't think this is guaranteed. The register allocator is told in which register every value needs to be at the start of the asm block, but it is free to ensure this in any way it wants. If for example the value happens to be in the right register from an earlier asm block, the register allocator will likely reuse the value rather than writing it again if it wasn't clobbered in the mean time. Or the register allocator could randomize certain allocation decisions to reduce the likelyhood of pathological behavior. Or the compiler may have stored the value on the stack and didn't optimize the stack store+load away. If you need the move to be directly before the syscall instruction, you will need to put the move in the asm block itself.

**Comment by bjorn3** [comment]
By the way rustc explicitly allows self-modifying code to change the content of asm blocks to any code that would have been allowed to be written in the asm blocks in the first place. This guarantee doesn't apply to code outside of the asm blocks however.

**Comment by jmillikin** [comment]
> If you need the move to be directly before the syscall instruction, you will need to put the move in the asm block itself.

I tried the naive way (`asm!("mov eax, {nr:e}", nr = in(reg) syscall_nr)`) but this results in the constant -> register mov still being placed at the beginning, and then a register -> register mov later. Using `reg("ecx")` or `out("rax")` might change which register the constant gets stored in, but still results in two `mov` instructions where the second isn't long enough for the gVisor magic.

I was able to get the desired behavior using LLVM assembly and the `nr` constraint code ("prefer integer constant, fall back to register") but I don't see any way to express that constraint code in Rust's `in()`  expression.

Is it possible that what I'm trying to do isn't currently possible in Rust's `asm!` macro?

--

Rust version with `asm!`, generates a `mov eax, eax; syscall` (unwanted):

```rust
// rustc --emit obj -O -C panic=abort -o hello-rs.o hello.rs
// ld --gc-sections -o hello-rs hello-rs.o

#![no_std]
#![no_main]

const STDOUT: u64 = 1;
const SYSCALL_EXIT: u64 = 60;
const SYSCALL_WRITE: u64 = 1;

#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! {
	loop {}
}

#[no_mangle]
unsafe fn _start() {
	let message: &str = "Hello, world!\n";

	// write(STDOUT, message, message.len())
	let mut _rc: i64;
	core::arch::asm!(
		"mov eax, {nr:e}",
		"syscall",
		nr = in(reg) SYSCALL_WRITE,
		in("rdi") STDOUT,
		in("rsi") message.as_ptr(),
		in("rdx") message.len(),
		out("rcx") _,
		out("r11") _,
		lateout("rax") _rc,
	);

	// exit(0)
	core::arch::asm!(
		"syscall",
		in("rax") SYSCALL_EXIT,
		in("rdi") 0,
		out("rcx") _,
		out("r11") _,
	);
}
```
||
\  /
```
0000000000401000 <_start>:
  401000:	50                   	push   rax
  401001:	48 8d 35 f8 0f 00 00 	lea    rsi,[rip+0xff8]        # 402000 <_start+0x1000>
  401008:	b8 01 00 00 00       	mov    eax,0x1
  40100d:	bf 01 00 00 00       	mov    edi,0x1
  401012:	ba 0e 00 00 00       	mov    edx,0xe
  401017:	89 c0                	mov    eax,eax
  401019:	0f 05                	syscall 
  40101b:	b8 3c 00 00 00       	mov    eax,0x3c
  401020:	31 ff                	xor    edi,edi
  401022:	0f 05                	syscall 
  401024:	58                   	pop    rax
  401025:	c3                   	ret    
```

LLVM version, generates `mov eax, 0x1; syscall` (exactly what I want):

```
; llc -o hello-ll.o hello.ll -filetype=obj
; ld -o hello-ll hello-ll.o

@.message = internal constant [14 x i8] c"Hello, world!\0A"

define void @_start() {
	%message_ptr = getelementptr [14 x i8], [14 x i8]* @.message , i64 0, i64 0

	; write(STDOUT, message, message_len)
	call i64 asm sideeffect inteldialect "mov eax, $1; syscall",
		"={rax},nr,{rdi},{rsi},{rdx},~{rcx},~{r11},~{dirflag},~{fpsr},~{flags}"
		( i32 1            ; {eax} SYSCALL_WRITE
		, i64 1            ; {rdi} STDOUT
		, i8* %message_ptr ; {rsi} message
		, i64 14           ; {rdx} message_len
		)

	; exit(0)
	call i64 asm sideeffect inteldialect "mov eax, $1; syscall",
		"={rax},n,{rdi},~{rcx},~{r11},~{dirflag},~{fpsr},~{flags}"
		( i32 60 ; {eax} SYSCALL_EXIT
		, i64 0  ; {rdi} exit_code
		)

	ret void
}
```
||
\  /
```
0000000000401000 <_start>:
  401000:	bf 01 00 00 00       	mov    edi,0x1
  401005:	be 00 20 40 00       	mov    esi,0x402000
  40100a:	ba 0e 00 00 00       	mov    edx,0xe
  40100f:	b8 01 00 00 00       	mov    eax,0x1
  401014:	0f 05                	syscall 
  401016:	31 ff                	xor    edi,edi
  401018:	b8 3c 00 00 00       	mov    eax,0x3c
  40101d:	0f 05                	syscall 
  40101f:	c3                   	ret    
```

**Comment by bjorn3** [comment]
The unstable [asm const](https://github.com/rust-lang/rust/issues/93332) feature allows writing something like

```rust
core::arch::asm!(
    "mov eax, {nr}",
    "syscall",
    nr = const SYSCALL_WRITE,
    in("rdi") STDOUT,
    in("rsi") message.as_ptr(),
    in("rdx") message.len(),
    out("rcx") _,
    out("r11") _,
    out("rax") _rc,
);
```

Here the part after `const` can be a const generic I believe, but it can't be a runtime determined value.

**Comment by jmillikin** [comment]
Ok, sounds like the answer is that there's no way to express this in stable Rust at the moment. Thank you for the detailed and helpful comments!

**Comment by BurntSushi** [comment]
For my own edification: do either of you know _why_ a `mov eax, eax` instruction is generated here?

**Comment by jmillikin** [comment]
> For my own edification: do either of you know _why_ a `mov eax, eax` instruction is generated here?

Speculation: the register allocator doesn't have visibility into the semantic meaning of the `asm!` block, so it doesn't realize that I'm moving the value to `eax`. It just sees "this block needs `nr` to be assigned to something" + "`eax` is available for use by inputs" and chooses it.

Using `asm_const` would be better, because then I could write the `mov` myself, and also make sure it gets populated from a constant value.
