### ISSUE TITLE
Outdated list of architectures for the support of asm!

### ISSUE THREAD

**Issue by mert-kurttutan** [rust-lang/reference#1403]
Hi,
On the webpage of rust reference, it seems that the list of supported arch for `asm!` is outdated,

Old list on reference: https://doc.rust-lang.org/reference/inline-assembly.html#
Updated list codegen: https://github.com/rust-lang/rust/blob/master/compiler/rustc_target/src/asm/mod.rs

Could you clarify which arch are supported (on nightly and stable)?

**Comment by ehuss** [comment]
The list appears to be up-to-date for the reference. The reference only documents what is stable in rust. Unstable support is documented at https://doc.rust-lang.org/nightly/unstable-book/language-features/asm-experimental-arch.html.

**Comment by mert-kurttutan** [comment]
Thanks alot. I was not able to find it.
If it is OK for the format of the reference, a link to the unstable list/issue would be helpful. (right after the list of stable arch support).
