### ISSUE TITLE
[BUG] opaque types document is too complicated for newbee

### ISSUE THREAD

**Issue by loynoir** [rust-lang/reference#1404]
Hi, rust-devs.

I'm a week-zero-newbee.

I found [opaque types document](https://rust-lang.github.io/chalk/book/clauses/opaque_types.html) is too complicated for newbee.

Within typescript, I have seen people **protect meaningful subset** using userland library [type-fest](https://www.npmjs.com/package/type-fest) like below.

```ts
type Odd = Opaque<number, 'Odd'>;
type Even = Opaque<number, 'Even'>;

function castOdd(n: number): Odd {
  if ((n % 2) === 1) {
    return n satisfies number as Odd
  } else {
    throw new Error()
  }
}

function castEven(n: number): Even {
  if ((n % 2) === 0) {
    return n satisfies number as Even
  } else {
    throw new Error()
  }
}
```

When missused, typescript will report error.

```ts
let odd: Odd
let even: Even

odd = castOdd(1)
even = castEven(2);

// @ts-expect-error
odd = 1;
// @ts-expect-error
even = 2;
// @ts-expect-error
odd = even
// @ts-expect-error
even = odd;
```

How to write equivalent code within rust?

```rust
    type Odd = u32;
    type Even = u32;

    let mut odd: Odd = castOdd(1);
    let mut even: Even = castEven(2);

    let _ = odd;
    let _ = even;

    // FIXME: should be error at compile time
    odd = 1;
    // FIXME: should be error at compile time
    even = 2;
    // FIXME: should be error at compile time
    odd = even;
    // FIXME: should be error at compile time
    even = odd;

    let _ = odd;
    let _ = even;
```

I guess [opaque types document](https://rust-lang.github.io/chalk/book/clauses/opaque_types.html) is what I want.

But it's too complicated for a week-zero-newbee.

**Comment by bjorn3** [comment]
https://rust-lang.github.io/chalk/book/clauses/opaque_types.html is not meant for end users. It is the documentation of the chalk trait solver, which at one point was expected to become the replacement of the current trait solver. This is no longer the case. Instead we are working on a new trait solver in tree. Either way the reference isn't meant for beginners either. https://doc.rust-lang.org/stable/book/ch10-02-traits.html#returning-types-that-implement-traits is the documentation of `-> impl Trait` meant for beginners.

Your example wouldn't use opaque types in rust however. Instead you would likely be using the newtype pattern which is documented at https://doc.rust-lang.org/stable/book/ch19-04-advanced-types.html#using-the-newtype-pattern-for-type-safety-and-abstraction. For example:

```rust
struct Odd(u32);
struct Even(u32);

fn try_as_odd(n: u32) -> Option<Odd> {
  if n % 2 == 1 {
    Some(Odd(n))
  } else {
    None
  }
}

fn try_as_even(n: u32) -> Option<Even> {
  if n % 2 == 0 {
    Some(Even(n))
  } else {
    None
  }
}


let odd = try_as_odd(1).unwrap();
let even = try_as_even(2).unwrap();
```

**Comment by loynoir** [comment]
If someone search here, typescript type-fest opaque rust equivalent

typescript

```ts
{
  type Odd1 = number;

  // type-fest
  type Odd2 = Opaque<number, 'Odd2'>
}
```

rust 

```rust
{
    type Odd1 = i64;
    struct Odd2(i64);
}
```
