### ISSUE TITLE
should have document on best practice about how to `throw custom error`

### ISSUE THREAD

**Issue by loynoir** [rust-lang/reference#1405]
Seperated document issue from previous

https://github.com/rust-lang/reference/issues/1404

From my newbee understanding

typescript `throw error` equivalent

```ts
    throw new Error("msg");
```

should be

```rust
    panic!("msg");
```

But typescript `throw custom error` equivalent seems very complicated.

```ts
class OddEvenError extends Error { }

function castOdd(): Odd {
    throw new OddEvenError('not odd')
}
```

```rust
    struct Odd(u32);

    #[derive(Debug)]
    struct OddEvenError {
        message: String,
    }

    impl OddEvenError {
        fn new(message: &str) -> Self {
            OddEvenError {
                message: message.to_string(),
            }
        }
    }

    impl Error for OddEvenError {}

    impl std::fmt::Display for OddEvenError {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{}", self.message)
        }
    }

    fn cast_odd() -> Result<Odd, Box<dyn Error>> {
        Err(Box::new(OddEvenError::new("not odd")))
    }

    cast_odd().expect("err");
```

**Comment by bjorn3** [comment]
The reference describes the rust language itself, not what idiomatic rust is, nor how to learn it as beginner. The [rust book](https://doc.rust-lang.org/stable/book/) is meant for learning rust. In this specific case [Chapter 9: Error Handling](https://doc.rust-lang.org/stable/book/ch09-00-error-handling.html) is relevant.

**Comment by ehuss** [comment]
As mentioned, the reference isn't intended for new learners, or for how to map concepts from another language to Rust. If you are having questions on how to do things, I suggest trying one of the user forums such as https://users.rust-lang.org/.

**Comment by loynoir** [comment]
Ah, sorry.

I mis-understood as this repo is for rust document team.
