### ISSUE TITLE
TupleStructPattern misses RestPattern

### ISSUE THREAD

**Issue by jdupak** [rust-lang/reference#1410]
https://rustwiki.org/en/reference/patterns.html#tuple-struct-patterns does not specify a variant with `RestPattern`, but it compilers: [Compiler Explorer example](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DEArgoKkl9ZATwDKjdAGFUtEywYgArKUcAZPAZMADl3ACNMYj0AB1QFQjsGFzcPb1JY%2BNsBAKDQlgiorktMayyGIQImYgJk908fK0wbRIqqghyQ8Mi9czba1IbK6o68gokASktUE2Jkdg5okzCAanNTG2WAQWWIPABmACZSZf2D8YBSPYAhc41N282AekflgBUAT2jMZffp4mW0FhlghIphjiRlrRUEx0MtDMtMKpWNF6AA6B6LFZUBirACOJiqmAgmwgAH0mMdUajxiAtuNlgBaS7YE6HZbnADsNzuy15yy4D05ABFBXdnssAJJUH7TZZmb7nABsGhYTECEAuyuOWGQBmI30IcIU7OVmKVGmWRFWmANBBOOIIIOW0wIiwIIAe4sxy2xy1V6vpnKuyypqPZHJFdw4k1onC8vE8HC0pFQnAASmY7Qo/nN2Qc9jxSO6k9HJgBrEAHHyxjiSBOaXipji8BQgDRFhuTOCwJBoFjROiRciUPsD%2BhRBh4YAIAi0d6kLAANzwcwAanhMAB3ADyX0ThZotAIkVbEDCDdIYUCVXenELV%2BYxHe27C2iaxcLfbYgm3DDnF6wMITGAJwxFoVtuF4LBVSMcQSwXPB9WaRdMAg5NESaExjzvXhAmPGtk1oPAwmIG8XCwC8CGIPAWBwyYqAMYAFHXLdd0YHCZEEEQxHYKROPkJQ1AvXQigMIwQFMcx9GI1tIEmVBojKCDGxQ4hqKwWSNWKUpEgcBhnFcOo9H8QJOnyboigyBIBH6TxLLiayGBGLpCm098WiGGpDNSIpGmaARWmGUzRgsyxPNsnpPOc8zCkmbMZjmCZ9Djet4KbZZJIIZBlknadZ3eHZcEICFznzLhxl4YstHGctK2rTg61IRNkybFs2w7EsuxgRAQBdN1hwgUdB2IYJWHmTLsq4VEOQOVF0PwIh1L0fguNEcQ%2BJWgSVHUeCRNITdSOiOjko4eMmovJttywt1nWlCacqnGc5x2Fx%2B2GvMCwqjrqtqg5JFRABOIHgZBkHFROxrmsbTg2vbKro1IbsesylhEIGobx1GthOHu3KnveXhMAWkg8HQZbZG49bpE2xRtuEnoSnc%2BwIEcCKihM3IXJiByyjZ9IecSaKxl8xn/PKcLvLstyxcC9pgq53yJZSKXeiCzmYqSqibVJtsYxS860vTTNlgAWQlNNlhYzdIgyzNsrx/LCuJ/5SoLY5XrHG3XfKyrO1%2B%2Bra1SlqYcsdr4Zqk6DiD6Hm2%2B0tSFU%2BJ7EkIA%3D)

**Comment by ehuss** [comment]
Sorry, I'm not clear what seems to be missing. The list of `TupleStructItems` is a sequence of `Pattern`, and `Pattern` includes `RestPattern`.

(It is explicitly listed in `TuplePatternItems`, but that is because the grammar is different in that case.)
