### ISSUE TITLE
macros-by-example: repetitions, example seems not correct

### ISSUE THREAD

**Issue by Desjajja** [rust-lang/reference#1422]
As is said in [this section](https://doc.rust-lang.org/beta/reference/macros-by-example.html#repetitions):
>  ```A metavariable must appear in exactly the same number, kind, and nesting order of repetitions in the transcriber as it did in the matcher. So for the matcher $( $i:ident ),*, the transcribers => { $i }, => { $( $( $i)* )* }, and => { $( $i )+ } are all illegal, but => { $( $i );* } is correct and replaces a comma-separated list of identifiers with a semicolon-separated list.```

But I tried this on[ rust playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=4235874b6462e027e4fb9487060416fe) and the macro doesn't expand as expected as for the **comma-to-semicolon replacement**:
```rust
macro_rules! random_match {
    ($( $i:ident ),*)  => {
        [$( $i);*]
    }
}

fn main() {
    let (a, b, c): u32;
    random_match!(a, b, c);
}
```
the error from macro expansion said:
```bash
Standard Error
   Compiling playground v0.0.1 (/playground)
error: expected one of `!`, `.`, `::`, `?`, `]`, `{`, or an operator, found `;`
 --> src/main.rs:4:16
  |
4 |         [$( $i);*]
  |                ^ expected one of 7 possible tokens
```

**Comment by ehuss** [comment]
Sorry, I'm not quite following how it doesn't appear correct. In your example, the compiler is correct that `[a;b;c;]` is invalid syntax. Arrays must either use commas (`[a, b, c]`) or a single semicolon for a repeat const expression (`[a;b]`).
You can remove the square brackets in the macro, and it should work as a sequence of statements (if you also repair the other errors in the example).

**Comment by Desjajja** [comment]
> Sorry, I'm not quite following how it doesn't appear correct. In your example, the compiler is correct that `[a;b;c;]` is invalid syntax. Arrays must either use commas (`[a, b, c]`) or a single semicolon for a repeat const expression (`[a;b]`). You can remove the square brackets in the macro, and it should work as a sequence of statements (if you also repair the other errors in the example).

 my point is ` $( $i:ident ),*, => { $( $i );* }` doesn't expand into what this section implies would be a replacement from `,` to `;`

**Comment by Desjajja** [comment]
> Sorry, I'm not quite following how it doesn't appear correct. In your example, the compiler is correct that `[a;b;c;]` is invalid syntax. Arrays must either use commas (`[a, b, c]`) or a single semicolon for a repeat const expression (`[a;b]`). You can remove the square brackets in the macro, and it should work as a sequence of statements (if you also repair the other errors in the example).

Yeah, ur absolutely right, I didn't noticed the square brackets, thanks a lot.
