### ISSUE TITLE
return expressions is a expression，Why add a semicolon after an return expression？

### ISSUE THREAD

**Issue by 583654109** [rust-lang/reference#1469]
return a is ok
why <return a;>?
why <;> ?
##################################################
[return expressions](https://doc.rust-lang.org/stable/reference/expressions/return-expr.html#return-expressions)
Syntax
ReturnExpression :
   return [Expression](https://doc.rust-lang.org/stable/reference/expressions.html)?

Return expressions are denoted with the keyword return. Evaluating a return expression moves its argument into the designated output location for the current function call, destroys the current function activation frame, and transfers control to the caller frame.

An example of a return expression:

fn max(a: i32, b: i32) -> i32 {
    if a > b {
        return a;
    }
    return b;
}

**Comment by ehuss** [comment]
I think it is just a stylistic convention to turn it into a statement. 

This issue tracker probably isn't the best place to ask questions about *why* Rust is the way it is. I'd suggest using one of the user forums such as https://users.rust-lang.org/.
