### ISSUE TITLE
Clarify the status of paragraph identifiers

### ISSUE THREAD

**Issue by mattheww** [rust-lang/reference#1573]
I see the master branch now contains some of the new C++-style paragraph identifiers (strings like `[asm.rules.mem-same-as-ffi]`).

I think it's important that the Reference's introduction should say something about what those identifiers are, and what expectations readers should have about their stability.

(In the C++ world, these identifiers have historically been very stable between standards and drafts, and of course each standard itself lasts for several years.)

Is there an intention that as long as a particular identifier is present the text it covers will have the same meaning (assuming the Rust language itself doesn't change)?

Should readers expect that when the Reference's text is improved the previously-existing identifiers will still be present?

In particular, it would be good to say whether it's reasonable to rely on these identifiers from an external long-lasting document, without also quoting the text or noting the version of the Reference it came from.

For example, is it appropriate to use these identifiers in a Rust RFC?

**Comment by ehuss** [comment]
Yea, we definitely should have that documented. I'll open a PR soon to add a description of what the rules are.

For the short term, I think we will say that the identifiers won't be stable as we may be reworking some parts. However our goal is definitely to have them be stable (or at least with redirects if we ever rename things).
