### ISSUE TITLE
Document restrictions on use of generics in const contexts in type position

### ISSUE THREAD

**Issue by traviscross** [rust-lang/reference#1581]
As raised here:

- https://github.com/rust-lang/reference/pull/1566/files#r1713027968

...related to the language:

> Const contexts that are used as parts of types (array type and repeat length expressions as well as const generic arguments) can only make restricted use of surrounding generic type and lifetime parameters.

We should document what these restrictions are precisely.

Here's an example of what doesn't work:

```rust
fn foo<const C: usize>() {
    let _ = [(); const { C + 1 }];
    //~^ ERROR generic parameters may not be used in const operations
}
```

Similarly:

```rust
trait Tr {
    const C: usize;
}

impl Tr for () {
    const C: usize = 0;
}

fn foo<T: Tr>() {
    let _ = [(); const { T::C }];
    //~^ ERROR constant expression depends on a generic parameter
}
```

cc @RalfJung @ehuss @BoxyUwU

**Comment by RalfJung** [comment]
We should probably also emit more specific errors -- it is not wrong for "constant expression [to depend] on a generic parameter", it's just wrong in this specific case where that expression occurs in a type.

Also, strange that the two examples above lead to different errors that say the same thing in different words -- they must be caught by different checks, somehow?
