### ISSUE TITLE
Clarify "immutable bytes" definition

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/reference#1616]
Currently, we define "immutable bytes" as

> All bytes inside a [const](https://doc.rust-lang.org/nightly/reference/items/constant-items.html) item or within an implicitly [const-promoted](https://doc.rust-lang.org/nightly/reference/destructors.html#constant-promotion) expression are immutable. The bytes owned by an immutable binding or immutable static are immutable, unless those bytes are part of an [UnsafeCell<U>](https://doc.rust-lang.org/nightly/core/cell/struct.UnsafeCell.html).

However, there are some issue with this. First of all, a const item can only be used as a value, not as a place, so it doesn't really "contain" bytes that could be (im)mutable -- except if it is subject to lifetime extension, as in
```rust
const C: &Vec<i32> = &Vec::new();
```

Secondly, for `static`, the actual rule is that for bytes inside lifetime-extended values, they are *all* immutable. `UnsafeCell` makes no difference.

**Comment by chorman0773** [comment]
I have a few ideas about how to write it, for varying levels of rigor. I think that in terms of lifetime extension, const-promotion occurs for both `static` and `const` items, correct? I'd expect that the const-promotion rule would apply there as well.

**Comment by RalfJung** [comment]
Const promotion and lifetime extension are largely orthogonal mechanisms. I was talking about lifetime extension above.

**Comment by chorman0773** [comment]
Ok, then I'd probably say
> All bytes within a const-promoted expression, or a lifetime-extended expression in the initializer of a `static` or `const` item are immutable. All bytes owned (directly) by an immutable binding or immutable `static` are immutable, except bytes within an [`core::cell::UnsafeCell`].

**Comment by RalfJung** [comment]
Yeah, that sounds good.
