### ISSUE TITLE
missing attribute and derive macro namespaces

### ISSUE THREAD

**Issue by lolbinarycat** [rust-lang/reference#1621]
the [namespaces](https://doc.rust-lang.org/reference/names/namespaces.html) section describes 5 namespaces: type, value, macro, lifetime, and label, but there are two more, both related to proc macros:
* the derive namespace, essential for the operation of crates like `derive_more`
* the attribute namespace, used by attribute macros, as well as tool attributes

**Comment by ehuss** [comment]
The macro namespace is split into two [sub-namespaces](https://doc.rust-lang.org/reference/names/namespaces.html#sub-namespaces) where I believe what you are looking for resides. I'm not aware of derives existing in a separate namespaces from attributes. Can you show an example of that?

**Comment by lolbinarycat** [comment]
i stand corrected.
