### ISSUE TITLE
Spec identifiers are visible on Destructors page

### ISSUE THREAD

**Issue by Tomer-Eliahu** [rust-lang/reference#1672]
Apologies if this was intended. 

I noticed the change on the destructors page.

I guessed this was unintended because for almost all other pages spec identifiers were added (based on #1561), the spec identifiers are not visible. The spec identifiers are only visible for [Inline assembly](https://doc.rust-lang.org/reference/inline-assembly.html#inline-assembly) and [Destructors](https://doc.rust-lang.org/reference/destructors.html#destructors). 

If this is intended (and the future for what the rest of reference would look like), I think an option to hide/show these spec identifiers would be nice.

**Comment by chorman0773** [comment]
It's supposed to be visible on all pages that have them. If you are looking at the stable or beta reference, not all of the PRs might be on that version yet.
