### ISSUE TITLE
The reference is wrong about constants referencing statics since v1.83.0

### ISSUE THREAD

**Issue by HeCorr** [rust-lang/reference#1690]
Hello! I've noticed that the Rust 1.83.0 announcement [mentions](https://blog.rust-lang.org/2024/11/28/Rust-1.83.0.html#new-const-capabilities) that it is now possible to reference `static` items in `const` contexts:
```Rust
static S: i32 = 25;
const C: &i32 = &S;
```

But the Rust Reference still [says](https://doc.rust-lang.org/reference/items/static-items.html) it is not:
> All access to a static is safe, but there are a number of restrictions on statics:
> - The type must have the `Sync` trait bound to allow thread-safe access.
> - **Constants cannot refer to statics.**

I am willing to write a PR for this but I am not sure what the best course of action is. Simply removing that bullet-point would mean having to rephrase the text above it, but I don't know what would sound best (also, a single bullet-point may look weird).

What should I do?

**Comment by chorman0773** [comment]
#1610 already addresses it, but there's editorial issues.

**Comment by HeCorr** [comment]
Oops, my bad. instead of searching for existing issues/PRs I merely checked the date of the most recent ones since the update announcement was published and found none. I should have looked further. I apologize.

You may close this if you want.
