### ISSUE TITLE
Never type was unstabilized

### ISSUE THREAD

**Issue by Havvy** [rust-lang/reference#344]
We need to back out #206 until it's re-stabilized.

**Comment by ehuss** [comment]
@Centril I'm guessing that the reference should probably include more detail on the never type (https://github.com/rust-lang/reference/blob/master/src/types/never.md is pretty slim), would you agree?  Is that something you'd like to do?  If not, I can probably try to figure out what could be added, but an outline of what would be useful to add would be helpful.

(And congratulations on getting it stabilized. 😄 )

**Comment by Centril** [comment]
@ehuss It seems roughly in good shape, but I would probably extend that with:

- An explanation of that it is equivalent to `enum Void {}` except for the implicit coercion behavior. -- contrast & compare.
- A note wrt. the inference fallback being `()` (for now, with a link to https://github.com/rust-lang/rust/issues/65992).

If you have a sec to file the PR that would be neat!

> (And congratulations on getting it stabilized. 😄 )

Thanks! (I wonder how long it lasts... 😅)

**Comment by ehuss** [comment]
Closing this as it has been re-stabilized. https://github.com/rust-lang/rust/pull/65355
