### ISSUE TITLE
Add "niche" to the glossary

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/reference#535]
I have seen the term "niche" come up recently during discussions related to enum layout optimizations.

I have inferred that the technical term "niche", as in the "a niche for a type T", means something along the lines of:
> a bit pattern that has the same bit-width as the size of T but is explicitly *not* a valid value for type T. A niche for a type can be used to store data from the outer context of where the type is located. For example, `Box<u32>` can never be null, so we can use the null bit pattern to represent `Option::<Box<u32>>::None` without having to allocate any extra bits.

We should find a more elegant way to phrase the definition, and then add it to the glossary.

**Comment by Havvy** [comment]
From the perspective of the reference, enum layout optimizations are not a defined part of the language at all, so we don't actually discuss it. As such, if we added `niche` to the glossary, it wouldn't tie to anything in the reference itself.

**Comment by ehuss** [comment]
The [rustc glossary](https://rust-lang.github.io/rustc-guide/appendix/glossary.html) might be a good place for this.

**Comment by ehuss** [comment]
I'm moving this to the rustc-dev-guide (https://github.com/rust-lang/rustc-dev-guide/issues/664).  If and when the reference starts using the term, we can add it to the glossary here, too.
