### ISSUE TITLE
Array type should say size expression is a *const* expression.

### ISSUE THREAD

**Issue by ehuss** [rust-lang/reference#582]
The array size expression needs to be a const expression (I believe). Currently types/array.md only says that it needs to evaluate to `usize`.

**Comment by Centril** [comment]
Yep, that's right. Moreover, currently, the const expression acts as an anonymous constant, so:
```rust
fn foo<T>() { let x: [u8; core::mem::size_of::<T>()]; }
```
is not valid (but this may change...)

**Comment by ehuss** [comment]
cc https://github.com/rust-lang/rust/issues/43408
