### ISSUE TITLE
Document that isize/usize are at least 16-bit wide on all platforms we currently support

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/reference#643]
See this UCG PR: https://github.com/rust-lang/unsafe-code-guidelines/pull/154

@briansmith raised the issue that this guarantee would be more useful if it was documented elsewhere and they are right. We should document that here, in the `isize`/`usize` API docs, and maybe also on the trait impls justified by this observation, like the `From<u16>` impl for `usize`, for example.

**Comment by Centril** [comment]
Sure, this seems reasonable to specify somewhere... but which section exactly... perhaps a new one "Assumptions about the platform"?

cc @ehuss

**Comment by gnzlbg** [comment]
Some trait impls are justified by this assumption, but we can't really attach documentation to trait impls AFAICT.

**Comment by Centril** [comment]
> but we can't really attach documentation to trait impls AFAICT.

AFAIK we can actually.

**Comment by ehuss** [comment]
I would just include the minimum at https://doc.rust-lang.org/reference/types/numeric.html#machine-dependent-integer-types.
