### ISSUE TITLE
Description of place expressions is incomplete

### ISSUE THREAD

**Issue by jturner314** [rust-lang/reference#727]
According to [Assignment expressions](https://doc.rust-lang.org/nightly/reference/expressions/operator-expr.html#assignment-expressions), the left-hand-side of an assignment must be a place expression. Place expressions are described [here](https://doc.rust-lang.org/nightly/reference/expressions.html#place-expressions-and-value-expressions) as "paths which refer to local variables, static variables, dereferences (`*expr`), array indexing expressions (`expr[expr]`), field references (`expr.f`) and parenthesized place expressions. All other expressions are value expressions."

Based on this description, I wouldn't expect method calls to be allowed in place expressions. However, this does compile and run:

```rust
fn main() {
    let mut x = vec![1, 2, 3];
    x.as_mut_slice()[0] = 4;
    println!("{:?}", x);
}
```

([Rust playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e27901156513cf515ce0fd99da659565))

`x.as_mut_slice()[0]` is the left side of an assignment, so it must be a place expression. However, it contains a method call.

Here's another example containing a method call:

```rust
#[derive(Debug)]
struct Foo {
    x: i32,
}

impl Foo {
    fn x_mut(&mut self) -> &mut i32 {
        &mut self.x
    }
}

fn main() {
    let mut f = Foo { x: 1 };
    *f.x_mut() = 2;
    println!("{:?}", f);
}
```

([Rust playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5de4439cf90b5339ad68385c1b14cafa))

I'm not really sure what the correct description of place expressions is, but the current description in the reference appears incomplete since it doesn't indicate that method calls are allowed.

Edit: I just noticed that a very similar description also appears in the help for compiler error [E0067](https://doc.rust-lang.org/stable/error-index.html#E0067).

**Comment by matthewjasper** [comment]
When the text says "indexing expressions" it means all indexing expressions, with no restrictions on the operands.

**Comment by jturner314** [comment]
Oh, I see. `expr` in the `*expr`, `expr[expr]`, and `expr.f` refers to general expressions, not just place expressions. Thanks, and sorry for the confusion.
