### ISSUE TITLE
Examples of coercions are wrong

### ISSUE THREAD

**Issue by martin-t** [rust-lang/reference#734]
Several of the examples on [the coercions page](https://doc.rust-lang.org/stable/reference/type-coercions.html) claim that 42 gets coerced into i8. However, no conversion takes place, the 42 is i8 already thanks to type inference.

Potentially related PR: #342

**Comment by thepowersgang** [comment]
A more suitable type pair would be `&String` and `&str` (which is a deref coercion), or `&Foo` and `&dyn TraitFooImpls`
