### ISSUE TITLE
Wrong grammar for `match`.

### ISSUE THREAD

**Issue by steffahn** [rust-lang/reference#774]
[In the grammar for `match`](https://doc.rust-lang.org/nightly/reference/expressions/match-expr.html), i.e. for the nonterminal `MatchExpression`, in `MatchArms` the right-hand side of the non-last arms only allows skipping the `,` for `BlockExpression`. However [it seems to be the case](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1114d1a7917ae89458b351017ea1d49e) that any `ExpressionWithBlock` works without the `,`. _Is this correct?_

Furthermore, currently the case of a `BlockExpression` followed by `,` matches both alternatives of the `BlockExpression ,? | Expression ,`. Perhaps a nicer rule would use `ExpressionWithoutBlock , | ExpressionWithBlock ,?`, in effect being similar to my proposed rule for `ExpressionStatement` in #773, but with comma instead of semicolon.

Finally, in the last arm, the `BlockExpression | Expression` part seems a bit redundant as a `BlockExpression` is an `Expression`.

**Comment by ehuss** [comment]
This all sounds like good changes to me.
