### ISSUE TITLE
enum documentation not updated for RFC 2195

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/reference#786]
https://doc.rust-lang.org/reference/items/enumerations.html#custom-discriminant-values-for-field-less-enumerations talks about "Custom Discriminant Values for Field-Less Enumerations", but does not mention at all that since https://github.com/rust-lang/rfcs/blob/master/text/2195-really-tagged-unions.md Rust also supports custom discriminant values and defined layout for enums with fields.

**Comment by ehuss** [comment]
It looks like there was an attempt to do this at #246 that wasn't completed.

**Comment by Havvy** [comment]
cc-ing @poliorcetics as requested in Zulip.
