### ISSUE TITLE
If let and while let examples of irrefutable patterns should mention warning

### ISSUE THREAD

**Issue by alercah** [rust-lang/reference#799]
Both [`if let`][1] and [`while let`][2] have examples with irrefutable patterns. By default this is a compiler warning, so they make bad examples, or at least deserve mention of the compiler warning.

There should also probably be more links on these pages to the definition of irrefutable.

[1]: https://doc.rust-lang.org/nightly/reference/expressions/if-expr.html#if-let-expressions
[2]: https://doc.rust-lang.org/nightly/reference/expressions/loop-expr.html#predicate-pattern-loops

**Comment by rimutaka** [comment]
As per discussion with @ehuss (https://github.com/rust-lang/reference/pull/835#discussion_r451035016)
> In general, the reference does not cover rustc lints, so I don't think it is appropriate to add this.

If that is true, this issue should be closed making PR #835 redundant.

**Comment by traviscross** [comment]
For the reasons mentioned there, we'll go ahead and close this.
