### ISSUE TITLE
List of permitting structures in const functions is out of date

### ISSUE THREAD

**Issue by alercah** [rust-lang/reference#800]
The list [here](https://doc.rust-lang.org/nightly/reference/items/functions.html#const-functions) of things permitted in const functions is out of date, and has been since at least [1.33.0](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1330-2019-02-28) when `let` bindings, assignments, and other constructs were allowed.

**Comment by ehuss** [comment]
Closing, as I believe the list is now up-to-date via #842, #867, and #883.  If there is anything still missing, feel free to reopen or open a new issue.
