### ISSUE TITLE
No mention of `self` in `extern crate` declarations.

### ISSUE THREAD

**Issue by alercah** [rust-lang/reference#801]
rust-lang/rust#57407 made it possible to refer to `self` in `extern crate _ as _;` items to alias the current crate. This is not mentioned on the [`extern crate` page](https://doc.rust-lang.org/nightly/reference/items/extern-crates.html#underscore-imports).

**Comment by ehuss** [comment]
I think this was done in #517. Is there something missing?

**Comment by alercah** [comment]
Ah, I was looking on the wrong section of the page. Thanks!
