### ISSUE TITLE
The supported encoding of Rust source code is not documented

### ISSUE THREAD

**Issue by upsuper** [rust-lang/reference#804]
Although it seems like a common sense that Rust only supports source code in UTF-8, it doesn't seem to be explicitly mentioned in the reference. In the "Crates and source files" section, it only states:
> The optional UTF8 byte order mark (UTF8BOM production) indicates that the file is encoded in UTF8.

but doesn't mention what if there is no BOM there.

It should probably be mentioned that Rust source file is always in UTF-8 or something like that.

**Comment by ehuss** [comment]
The input format is stated here: https://doc.rust-lang.org/reference/input-format.html

**Comment by upsuper** [comment]
Oh, thanks!
