### ISSUE TITLE
Document `#[doc(alias="...")]`

### ISSUE THREAD

**Issue by sam-ka** [rust-lang/reference#913]
I apologize if this isn't the right repository for this issue. I didn't find documentation about this attribute in either [The Rustdoc Book](https://doc.rust-lang.org/stable/rustdoc/the-doc-attribute.html) or [The Rust Reference](https://doc.rust-lang.org/stable/reference/attributes.html).

**Comment by ehuss** [comment]
It is documented here: https://doc.rust-lang.org/rustdoc/advanced-features.html#add-aliases-for-an-item-in-documentation-search

**Comment by sam-ka** [comment]
My bad. When I couldn't find it with the rest of `doc`'s arguments and google couldn't give me a relevant result, I just assumed the feature wasn't documented. I'll close this issue.

Out of curiosity, do you know why `alias` wasn't documented under `The #[doc] attribute` like other doc arguments?

**Comment by ehuss** [comment]
I do not know why, it seems reasonable that the chapter on `#[doc]` should include everything. If you'd like, you can follow up with the rustdoc team either on the [rust-lang/rust repo](https://github.com/rust-lang/rust/) where the docs live, or on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc).
