### ISSUE TITLE
Test failing for the master branch

### ISSUE THREAD

**Issue by saki-osive** [rust-lang/reference#954]
Hi, the tests run after executing the command

```
mdbook test
```
fail after the first pull. Are we not actively pursuing the tests passing for now or am I inferring something incorrectly?
Thanks.

**Comment by Havvy** [comment]
Are you running them using a recent nightly version? If not, you'll get failures for things that have stabilized in nightly but haven't yet ridden the release train like (min) const generics.

**Comment by saki-osive** [comment]
Hi @Havvy, yes I didn't use the nightly version for the tests, will try it that way. Thanks.
