### ISSUE TITLE
Documentation for the dereference operator is circular

### ISSUE THREAD

**Issue by not-an-aardvark** [rust-lang/reference#973]
I'm trying to figure out the specifics of what the dereference operator does, based on the [documentation here](https://doc.rust-lang.org/reference/expressions/operator-expr.html#the-dereference-operator):

> The `*` (dereference) operator is also a unary prefix operator. When applied to a pointer it denotes the pointed-to location. If the expression is of type `&mut T` or `*mut T`, and is either a local variable, a (nested) field of a local variable or is a mutable place expression, then the resulting memory location can be assigned to. Dereferencing a raw pointer requires `unsafe`.
>
> On non-pointer types `*x` is equivalent to `*std::ops::Deref::deref(&x)` in an immutable place expression context and `*std::ops::DerefMut::deref_mut(&mut x)` in a mutable place expression context.

It seems like this definition is circular, and doesn't terminate. Is there a base case missing for when `x` is a reference? Based on the [`impl Deref<Target=T>` for `&'_ T`](https://doc.rust-lang.org/src/core/ops/deref.rs.html#77-83), it seems like `*&x` would expand to `**&&x`, which would expand to `**&*&&x`, etc. Given that this doesn't halt, I suspect the compiler special-cases `*` for references and that impl is just there to satisfy the type system. But if so, that special case is missing from the documentation, so it's still not clear what the `*` operator does.

I would make a PR, but I'm not sure what the correct description is. (I have an informal understanding of `*` in the C sense, i.e. "get the value pointed to by this reference", but it's not clear how this interacts with the borrow checker, since it seems like it's an important invariant that someone can't just cast `&T` to `T` to get ownership of something.)

**Comment by bjorn3** [comment]
The `Deref::deref` call only applies for **non-pointer** types. If `x` is a reference, there is thus no `Deref::deref` call.

**Comment by not-an-aardvark** [comment]
Thanks. My interpretation of "pointer" as used in that documentation was that it refers to the [raw pointer](https://doc.rust-lang.org/std/primitive.pointer.html) primitive, which wouldn't include references (although I see how this could be ambiguous). Would it make sense for me to update the docs to replace "pointer" there with something like "pointer or reference"?

**Comment by not-an-aardvark** [comment]
Actually, I just realized that "pointer" is linked to a [separate page](https://doc.rust-lang.org/reference/types/pointer.html) that describes references as a type of pointer. So this is probably adequately explained.

I've occasionally heard raw pointers colloquially referred to as "pointers", and I'd never heard references referred to as "pointers" (except when explaining them in terms of a C analog), so this was a bit confusing before noticing that "pointer" linked to a definition. But I'm not sure there's an easy improvement to this page in particular.

**Comment by Havvy** [comment]
I think there's plenty of ways for the page to be improved. Most of the expressions pages even. I'll definitely take this as feedback when I'm next going over that page for content.
